services:
  - type: web
    name: syphoon-billing-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_CHANNEL_ID
        sync: false
      - key: ZOHO_CLIENT_ID
        sync: false
      - key: ZOHO_CLIENT_SECRET
        sync: false
      - key: ZOHO_REFRESH_TOKEN
        sync: false
      - key: ZOHO_API_DOMAIN
        sync: false
      - key: ZOHO_ORG_ID
        sync: false
